.eslintrc
package-lock.json
package.json
packages/appium-tizen-tv-driver/lib/driver.js
packages/appium-tizen-tv-driver/lib/rc-pair.js
packages/tizen-remote/lib/index.js
packages/tizen-remote/test/e2e/tizen-remote.e2e.spec.js
packages/tizen-remote/test/unit/tizen-remote.spec.js
packages/tizen-remote/tsconfig.json

This is technically breaking, but I changed the signature of the `TizenRemote` constructor so that the "options" object is a fully optional second arg, and the only required arg (`host`) is first.
The main aim here was to write a handful of unit tests, but they of course uncovered a few problems.

chore(tizen-remote): fix leaks, update API

---

packages/appium-tizen-tv-driver/lib/rc-pair.js

I changed the constructor signature and neglected to update `rc-pair`

fix(appium-tizen-tv-driver): correct params to TizenRemote constructor

---

.wallaby.js
package-lock.json
package.json
packages/tizen-remote/lib/index.js
packages/tizen-remote/package.json
packages/tizen-remote/test/e2e/tizen-remote.e2e.spec.js
packages/tizen-remote/test/unit/tizen-remote.spec.js

This change allows the token to be persisted to disk. The implementation uses lockfiles to avoid concurrent writes to the token cache across instances/processes/etc.
Location of cache & lockfile is OS-dependent.
* * *

feat(tizen-remote): token persistence

---

.eslintrc
.wallaby.js
package-lock.json
package.json
packages/appium-tizen-tv-driver/lib/cli/helpers.js
packages/appium-tizen-tv-driver/lib/cli/sdb.js
packages/appium-tizen-tv-driver/lib/cli/tizen.js
packages/appium-tizen-tv-driver/lib/desired-caps.js
packages/appium-tizen-tv-driver/lib/driver.js
packages/appium-tizen-tv-driver/lib/global.d.ts
packages/appium-tizen-tv-driver/lib/keymap.js
packages/appium-tizen-tv-driver/lib/scripts.js
packages/appium-tizen-tv-driver/lib/server.js
packages/appium-tizen-tv-driver/package.json
packages/appium-tizen-tv-driver/test/e2e/browser.d.ts
packages/appium-tizen-tv-driver/test/e2e/browser.js
packages/appium-tizen-tv-driver/test/e2e/driver.e2e.spec.js
packages/appium-tizen-tv-driver/test/global.d.ts
packages/appium-tizen-tv-driver/test/helpers.js
packages/appium-tizen-tv-driver/tsconfig.json
packages/tizen-remote/lib/index.js
packages/tizen-remote/lib/keys.js
packages/tizen-sample-app/index.html
packages/tizen-sample-app/js/main.js
test/setup.js
tsconfig.json

This PR adds support for keypresses via RC and chromedriver.  It needs some more tests.
Highlights:
- add a sample app for testing
- let `TizenRemote` force-get a new token
- use `executeMethodMap` to create `tizen: pressKey` and `tizen: longPressKey` methods
- extract chromedriver-executed scripts into their own module (`scripts.js`) and just wrap them when asking chromedriver to run a command
- add E2E tests which work with `tizen-sample-app`
- add types to `appium-tizen-tv-driver`
- add a `--port` flag to `rc-pair` script

feat(appium-tizen-tv-driver): keypress support

---

package-lock.json
packages/appium-tizen-tv-driver/lib/driver.js
packages/appium-tizen-tv-driver/test/e2e/driver.e2e.spec.js
packages/tizen-remote/lib/index.js

the only time when we should specifically force a new token is when `appium:resetRcToken` is `true`.
also, immediately after instantiation, unless a token has been provided to `TizenRemote` (or via the env), the `hasToken()` method may resolve `true`, but it will not actually _set_ the token in memory from the cache due to it being a naughty side-effect.  unless `getToken()` was explicitly called, the token would not be set in-memory from the cache before the connection attempt.  the logic has changed so that, at connection time, we attempt to load the token from cache if one exists (and cache persistence is enabled).  if one still doesn't exist after connection, then it will ask for a new one.
also fixes some typescript problems which may actually be a bug in typescript. …

fix(appium-tizen-tv-driver,tizen-remote): do not always force token

---

.wallaby.js
package-lock.json
package.json
packages/tizen-remote/index.js
packages/tizen-remote/lib/command.js
packages/tizen-remote/lib/tizen-remote.js
packages/tizen-remote/package.json
packages/tizen-remote/test/e2e/server.js
packages/tizen-remote/test/e2e/tizen-remote.e2e.spec.js
packages/tizen-remote/test/unit/tizen-remote.spec.js

Previously, the lib only updated the cached token (when persistence is enabled) when a) it wasn't present, or b) the `resetRcToken` cap was `true`.
Evidently (?) tokens can expire, so this adds a listener for _unexpected_ "new token" messages and updates the internal token and cache (if applicable) when such a msg is received.
- Also renamed `lib/index.js` to `lib/tizen-remote.js` for sanity purposes
- Expose getters `token` and `tokenCachePath`

feat(tizen-remote): update token when new one received

---

package-lock.json
packages/appium-tizen-tv-driver/lib/driver.js
packages/appium-tizen-tv-driver/test/unit/driver.spec.js

As per offline discussion, the current behavior is somewhat unexpected, so we'll just not do that.
Closes #89 ... hopefully.

do not send ENTER after setValue

---

packages/appium-tizen-tv-driver/lib/cli/helpers.js

On Windows, this should be `tizen.bat` and `sdb.exe` afaict.
Closes #119

fix(appium-tizen-tv-driver): windows compat Fix (I hope) paths to `tizen` and `sdb` executables on Windows

---

.github/workflows/build.yml

Hopefully this will resolve the "Renovate failed to look up the following dependencies: Could not determine new digest for update (datasource: github-tags)." warning we keep getting.

chore: reset action SHAs for renovate

---

package-lock.json
package.json
packages/tizen-remote/README.md
packages/tizen-remote/lib/tizen-remote.js
packages/tizen-remote/lib/types.ts
packages/tizen-remote/package.json
packages/tizen-remote/test/e2e/tizen-remote.e2e.spec.js
packages/tizen-remote/test/unit/tizen-remote.spec.js

BREAKING CHANGE: Uses a new scheme for token storage. Instead of a single JSON file, we use one file per device.  This will break existing token stores.  Also, the `name` option of the `TizenRemote` constructor is no longer recognized.
This replaces the bespoke token cache with the `@appium/strongbox` package.  As such, it mitigates the need for lockfiles.
* * *
_The build should fail until appium/appium#18480 is merged and released._

feat(tizen-remote): use per-host token storage

---

packages/appium-tizen-tv-driver/lib/cli/sdb.js
packages/appium-tizen-tv-driver/test/unit/sdb.spec.js

During testing on windows we found times when the strings returned from applist contained extra spaces which would cause problems.  When this happened the method _parseListAppsCmd would return no results which would cause automation to fail because the expected app was not installed.
Validated locally with a device which was showing the issue.
Added an additional unit test which had a string both with added spaces as well as trash on one line.  This allowed us to verify if we just see spaces at the end we are ok, but if we see trash then the line will be ignored.

Fix issue on windows when spaces were seen at the end of the lines while parsing the results of the applist call

---

packages/appium-tizen-tv-driver/lib/driver.js

If the test apps was not debuggable, current error returns:
```
Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Command 'sdb -s 192.168.11.41\:26101 shell 0 debug 9Ur5IzDKqV.TizenYouTube' exited with code 1. Stdout was: ''. Stderr was: 'closed '
from UnknownError: An unknown server-side error occurred while processing the command. Original error: Command 'sdb -s 192.168.11.41\:26101 shell 0 debug 9Ur5IzDKqV.TizenYouTube' exited with code 1. Stdout was: ''. Stderr was: 'closed '
```
which is not helpful since no idea what made the error.
So, this is a small tweak but maybe it would be slightly helpful the given package may not be debuggable:
```
Selenium::WebDriver::Error::SessionNotCreatedError: A new session …
```

chore: better error message

---

packages/appium-tizen-tv-driver/lib/cli/helpers.js

It could let the command keep running.
240000 comes from uia2's adb command default tiemout

chore: set default command timeout

---

packages/appium-tizen-tv-driver/lib/rc-pair.js

Print slightly better error log in https://github.com/headspinio/appium-tizen-tv-driver/pull/592 case:
error example:
```
The device 123.456.789.10 might be denied in the past pairing. Please make sure the device 123.456.789.10 had no denied devices, especially named '123.456.789.10'.
appium-tizen-tv-driver/node_modules/got/dist/source/as-promise/index.js:118
request._beforeError(new types_1.HTTPError(response));
^
HTTPError: Response code 401 (Unauthorized)
at Request.<anonymous> (/appium-tizen-tv-driver/node_modules/got/dist/source/as-promise/index.js:118:42)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
✖ Encountered an error when running 'pair-remote': Script "pair-remote" exited with code 1
```

chore: show explanation in the log when 401 occurrs

---

package-lock.json
packages/appium-tizen-tv-driver/lib/driver.js
packages/appium-tizen-tv-driver/lib/rc-pair.js
packages/tizen-remote/lib/tizen-remote.js
packages/tizen-remote/package.json
packages/tizen-remote/test/e2e/tizen-remote.e2e.spec.js
packages/tizen-remote/test/unit/tizen-remote.spec.js

- Do not raise an error while no app found in driver.js for older TVs
- Add `isTokenSupportedDevice` to check if the device supports token
- Modify pair's log message
- Prevent raising exception for non-token response by the device for old TVs (e.g. Year 2016 model)

fix: improved non token supported device handling

---

packages/appium-tizen-tv-driver/README.md
packages/appium-tizen-tv-driver/lib/cli/sdb.js
packages/appium-tizen-tv-driver/lib/driver.js
packages/appium-tizen-tv-driver/test/unit/sdb.spec.js

I learned
- tizen 2.5 and lower platform may not support chromedriver automation because of  the engine matter https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html
- `debug` command syntax could depend on the platform version
So, this PR does
1. not support JS mode (chromedriver automation) for lower than 2.4 tizentv platform version as imcompatibility. Instead, if the given caps uses `remote` mode, the session will work `rcOnly` mode
2. modify `debug` command syntax for 4.0+ or lower than 4.0.
Possibly this will close https://github.com/headspinio/appium-tizen-tv-driver/issues/584 also. This PR helps https://github.com/headspinio/appium-tizen-tv-driver/issues/548 as well.

feat: improve older platform version handling such as 2016

---

packages/appium-tizen-tv-driver/README.md
packages/appium-tizen-tv-driver/lib/cli/sdb.js
packages/appium-tizen-tv-driver/lib/driver.js

closes https://github.com/headspinio/appium-tizen-tv-driver/issues/601
Ideally, we'd like to terminate the app under test with this command before launching the app to avoid no response by `tizen run` / `sdb shell was_execute` command

feat: add activateApp/terminateApp ext command

---

packages/appium-tizen-tv-driver/README.md
packages/appium-tizen-tv-driver/lib/cli/tizen.js
packages/appium-tizen-tv-driver/lib/driver.js

https://github.com/headspinio/appium-tizen-tv-driver/issues/603 is perhaps a bug in the device side since https://developer.tizen.org/ko/development/tizen-studio/web-tools/running-and-testing-your-app/sdb?langredirect=1#install_uninstall (for example) addresses `sdb uninstall` but it does not work. (no error as well)
This PR tries to emphasize possible error cases as failure so that we could notice them by reading the log.
closes https://github.com/headspinio/appium-tizen-tv-driver/issues/603

chore: add better logging/error handling for tizen command

---

packages/appium-tizen-tv-driver/lib/driver.js
packages/appium-tizen-tv-driver/test/unit/driver.spec.js

As same as https://github.com/headspinio/appium-lg-webos-driver/pull/60 , but this is not necessary for tizentv in current our observation basis

fix: add mini browser version for non browser info case

---

packages/appium-tizen-tv-driver/README.md
packages/appium-tizen-tv-driver/lib/driver.js

https://github.com/headspinio/appium-tizen-tv-driver/pull/664 introduced `debug: true` behavior, but it was nice to extract the data clearing behavior from that.

feat: extract clearing local data from activateApp with debug: true to clearApp

---

packages/tizen-remote/lib/tizen-remote.js

Adds token unset if the ws got `ms.channel.timeOut`. Typically it occurs when the token is invalid. Ideally... we want to get unauthorized error or something but TVs seem not.
Then, re-using the existing token would keep failing. Instead, requesting a fresh token might be more helpful.

feat(tizen-remote): unset if the request got timeout in remote mode

---

packages/tizen-sample-app/README.md

This PR enhances the README.md for the Tizen sample app by providing clearer instructions on packaging the built project:
- Updated the tizen package command example to use a more descriptive placeholder: `<CERTIFICATE_PROFILE_NAME>`.
- Added a note explaining how to find the certificate profile name in Tizen Studio (`Tools > Certificate Manager`).
These changes improve usability by ensuring developers can easily locate and use the correct certificate profile when packaging their Tizen applications.

Improve Packaging Instructions in Tizen Sample App Documentation

---

packages/appium-tizen-tv-driver/README.md

This PR updates the Appium Tizen driver’s README.md to accurately reflect the default value of the appium:noReset capability

Fix noReset Capability Default Value in docs
